# Generated by Django 2.2.3 on 2019-07-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursetask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='departments',
            field=models.ManyToManyField(related_name='departments', to='nursetask.Department'),
        ),
    ]
