# Generated by Django 2.2.3 on 2019-07-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursetask', '0002_auto_20190713_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tdate',
            field=models.DateField(auto_now=True),
        ),
    ]
