# Generated by Django 2.2.3 on 2019-07-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursetask', '0004_auto_20190713_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='nid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='tid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
