# Generated by Django 2.2.3 on 2019-07-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursetask', '0005_auto_20190713_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
