# Generated by Django 2.2.3 on 2019-07-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursetask', '0006_auto_20190713_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='did',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facility',
            name='fid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='nid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='rid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='sid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
