# Generated by Django 2.2.3 on 2019-07-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursetask', '0009_auto_20190713_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
